//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobnation.Models
{
    using System;
    using System.Collections.Generic;
    
    using T4TS;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    [TypeScriptInterface]
    [JsonObject(MemberSerialization.OptIn)]
    public partial class Profile
    {
        public Profile()
        {
            this.Products = new HashSet<Product>();
            this.Receipts = new HashSet<Receipt>();
        }
    
    	[JsonProperty]
        public int Id { get; set; }
    	[JsonProperty]
        public string ProfileName { get; set; }
    	[JsonProperty]
        public string Email { get; set; }
    	[JsonProperty]
        public string Password { get; set; }
    	[JsonProperty]
        public string Data { get; set; }
    	[JsonProperty]
        public string ProfileTitle { get; set; }
    
    [TypeScriptMember(Ignore=true)]
        public virtual ICollection<Product> Products { get; set; }
    [TypeScriptMember(Ignore=true)]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
