//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobnation.Models
{
    using System;
    using System.Collections.Generic;
    
    using T4TS;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    [TypeScriptInterface]
    [JsonObject(MemberSerialization.OptIn)]
    public partial class ReceiptItem
    {
    	[JsonProperty]
        public int Id { get; set; }
    	[JsonProperty]
        public string Quantity { get; set; }
    
    [TypeScriptMember(Ignore=true)]
        public virtual Product Product { get; set; }
    [TypeScriptMember(Ignore=true)]
        public virtual Receipt Receipt { get; set; }
    }
}
