//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobnation.Models
{
    using System;
    using System.Collections.Generic;
    
    using T4TS;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    [TypeScriptInterface]
    [JsonObject(MemberSerialization.OptIn)]
    public partial class Receipt
    {
        public Receipt()
        {
            this.ReceiptItems = new HashSet<ReceiptItem>();
        }
    
    	[JsonProperty]
        public int Id { get; set; }
    	[JsonProperty]
        public string RecepientName { get; set; }
    	[JsonProperty]
        public string RecepientEmail { get; set; }
    	[JsonProperty]
        public string SignatureData { get; set; }
    	[JsonProperty]
        public string Notes { get; set; }
    
    [TypeScriptMember(Ignore=true)]
        public virtual Profile Profile { get; set; }
    [TypeScriptMember(Ignore=true)]
        public virtual ICollection<ReceiptItem> ReceiptItems { get; set; }
    }
}
