/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module MND {
    /** Generated from mobnation.Models.Product **/
    export interface Product {
        Id: number;
        ProductName: string;
        Data: string;
        ProductTitle: string;
        Profile: MND.Profile;
        ReceiptItems: MND.ReceiptItem[];
    }
    /** Generated from mobnation.Models.Profile **/
    export interface Profile {
        Id: number;
        ProfileName: string;
        Email: string;
        Password: string;
        Data: string;
        ProfileTitle: string;
        Products: MND.Product[];
        Receipts: MND.Receipt[];
    }
    /** Generated from mobnation.Models.Receipt **/
    export interface Receipt {
        Id: number;
        RecepientName: string;
        RecepientEmail: string;
        SignatureData: string;
        Notes: string;
        Profile: MND.Profile;
        ReceiptItems: MND.ReceiptItem[];
    }
    /** Generated from mobnation.Models.ReceiptItem **/
    export interface ReceiptItem {
        Id: number;
        Quantity: string;
        Product: MND.Product;
        Receipt: MND.Receipt;
    }
}
