/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module MNE {
    /** Generated from EmailEntities.ReceiptItem **/
    export interface ReceiptItem {
        name: string;
        qty: number;
        price: number;
        cost: number;
    }
    /** Generated from EmailEntities.SigData **/
    export interface SigData {
        lx: number;
        ly: number;
        mx: number;
        my: number;
    }
    /** Generated from EmailEntities.ReceiptData **/
    export interface ReceiptData {
        items: MNE.ReceiptItem[];
        recName: string;
        recEmail: string;
        isName: string;
        isSig: MNE.SigData[];
    }
}
